/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.6/userguide/multi_project_builds.html
 */

rootProject.name = "belajar-gradle"

// menghubungkan modul" library yg sudah dibuat dengan main modul
// hapus version kotlin pada modul" lain, karena sudah di define pada main projectnya
include("belajar-gradle-module")
include("belajar-gradle-utils")