/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package belajar.gradle

import belajar.gradle.module.Product
import belajar.gradle.utils.StringUtil

class App {
    val greeting: String
        get() {
            return "Hello world."
        }
}

fun main(args: Array<String>) {
    println(App().greeting)

    println("belajar kotlin")

    val product = Product("1", "Botol Minum")
    println(StringUtil.toUpper(product.name))
}
